/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio1.pkg2021;
import java.util.ArrayList;
/**
 *
 * @author juanr
 */
public class CalculadoraGrafica extends javax.swing.JFrame {
    public double NumeroTotal = 0;
    public ArrayList <CalculadoraGrafica.OperationChain> ListadoOperaciones = new ArrayList();
    /**
     * Creates new form CalculadoraGrafica
     */
    public CalculadoraGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoCalculadora = new javax.swing.JTextField();
        NUM7 = new javax.swing.JButton();
        NUM4 = new javax.swing.JButton();
        NUM1 = new javax.swing.JButton();
        NUM8 = new javax.swing.JButton();
        NUM5 = new javax.swing.JButton();
        NUM2 = new javax.swing.JButton();
        NUM6 = new javax.swing.JButton();
        NUM9 = new javax.swing.JButton();
        NUM3 = new javax.swing.JButton();
        PUNTO = new javax.swing.JButton();
        NUM0 = new javax.swing.JButton();
        SEN = new javax.swing.JButton();
        TAN = new javax.swing.JButton();
        MULTI = new javax.swing.JButton();
        SUMA = new javax.swing.JButton();
        DIV = new javax.swing.JButton();
        MENOS = new javax.swing.JButton();
        COS = new javax.swing.JButton();
        POT = new javax.swing.JButton();
        IGUAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);

        textoCalculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCalculadoraActionPerformed(evt);
            }
        });

        NUM7.setText("7");
        NUM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM7ActionPerformed(evt);
            }
        });

        NUM4.setText("4");
        NUM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM4ActionPerformed(evt);
            }
        });

        NUM1.setText("1");
        NUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM1ActionPerformed(evt);
            }
        });

        NUM8.setText("8");
        NUM8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM8ActionPerformed(evt);
            }
        });

        NUM5.setText("5");
        NUM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM5ActionPerformed(evt);
            }
        });

        NUM2.setText("2");
        NUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM2ActionPerformed(evt);
            }
        });

        NUM6.setText("6");
        NUM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM6ActionPerformed(evt);
            }
        });

        NUM9.setText("9");
        NUM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM9ActionPerformed(evt);
            }
        });

        NUM3.setText("3");
        NUM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM3ActionPerformed(evt);
            }
        });

        PUNTO.setText(".");
        PUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOActionPerformed(evt);
            }
        });

        NUM0.setText("0");
        NUM0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM0ActionPerformed(evt);
            }
        });

        SEN.setText("sen");
        SEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENActionPerformed(evt);
            }
        });

        TAN.setText("tan");
        TAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TANActionPerformed(evt);
            }
        });

        MULTI.setText("x");
        MULTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIActionPerformed(evt);
            }
        });

        SUMA.setText("+");
        SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMAActionPerformed(evt);
            }
        });

        DIV.setText("/");
        DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVActionPerformed(evt);
            }
        });

        MENOS.setText("-");
        MENOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENOSActionPerformed(evt);
            }
        });

        COS.setText("cos");
        COS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COSActionPerformed(evt);
            }
        });

        POT.setText("Pon");
        POT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POTActionPerformed(evt);
            }
        });

        IGUAL.setText("=");
        IGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGUALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(textoCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NUM0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUM4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUM7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NUM5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NUM8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NUM6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NUM9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NUM3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MULTI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SUMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(POT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(COS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MENOS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IGUAL, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textoCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NUM9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NUM3)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NUM0)
                                .addComponent(PUNTO)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(SUMA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MULTI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SEN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TAN))
                        .addComponent(IGUAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MENOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DIV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(POT)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "+"));
        
    }//GEN-LAST:event_SUMAActionPerformed

    private void DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "/"));
        
    }//GEN-LAST:event_DIVActionPerformed

    private void MENOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENOSActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "-"));
    }//GEN-LAST:event_MENOSActionPerformed

    private void COSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COSActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "COS"));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        NumeroTotal = 0;
    }//GEN-LAST:event_COSActionPerformed

    private void POTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POTActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "POT"));
    }//GEN-LAST:event_POTActionPerformed

    private void NUM0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM0ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"0");
        NumeroTotal = Double.parseDouble(numero+"0");
    }//GEN-LAST:event_NUM0ActionPerformed

    private void NUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM1ActionPerformed
        // TODO add your handling code here:
          String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"1");
        NumeroTotal = Double.parseDouble(numero+"1");
    }//GEN-LAST:event_NUM1ActionPerformed

    private void NUM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM5ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"5");
        NumeroTotal = Double.parseDouble(numero+"5");
    }//GEN-LAST:event_NUM5ActionPerformed

    private void NUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM2ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"2");
        NumeroTotal = Double.parseDouble(numero+"2");
    }//GEN-LAST:event_NUM2ActionPerformed

    private void NUM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM3ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"3");
        NumeroTotal = Double.parseDouble(numero+"3");
    }//GEN-LAST:event_NUM3ActionPerformed

    private void NUM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM4ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"4");
        NumeroTotal = Double.parseDouble(numero+"4");
    }//GEN-LAST:event_NUM4ActionPerformed

    private void NUM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM6ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"6");
        NumeroTotal = Double.parseDouble(numero+"6");
    }//GEN-LAST:event_NUM6ActionPerformed

    private void NUM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM7ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"7");
        NumeroTotal = Double.parseDouble(numero+"7");
    }//GEN-LAST:event_NUM7ActionPerformed

    private void NUM8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM8ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"8");
        NumeroTotal = Double.parseDouble(numero+"8");
    }//GEN-LAST:event_NUM8ActionPerformed

    private void NUM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM9ActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+"9");
        NumeroTotal = Double.parseDouble(numero+"9");        
    }//GEN-LAST:event_NUM9ActionPerformed

    private void PUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOActionPerformed
        // TODO add your handling code here:
        String numero=textoCalculadora.getText();
        textoCalculadora.setText(numero+".");
        NumeroTotal = Double.parseDouble(numero+".");
    }//GEN-LAST:event_PUNTOActionPerformed

    private void MULTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "*"));
    }//GEN-LAST:event_MULTIActionPerformed

    private void textoCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCalculadoraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textoCalculadoraActionPerformed

    private void IGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGUALActionPerformed
        // TODO add your handling code here:
        double total = 0;
        CalculosCalculadora calculadora = new CalculosCalculadora();
        CalculadoraGrafica.OperationChain item;
        String operacionactual = null;
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        for (int i = 0; i < ListadoOperaciones.size(); i++) {
            item = ListadoOperaciones.get(i);
            if(item.operacion != null)
            {
                operacionactual = item.operacion;
            }
            if(item.operacion == null)
            {
                if (operacionactual == null)
                {
                    total = item.Numero;
                }
                else
                {
                    switch (operacionactual)
                    {
                        case "+":
                            total = calculadora.Suma((float) total, (float) item.Numero);                            
                            break;
                        case "-":
                            total = calculadora.Resta((float) total, (float) item.Numero);
                            break;
                        case "*":
                            total = calculadora.Multiplicacion((float) total, (float) item.Numero);
                            break;
                        case "/":
                            total = calculadora.Division((float) total, (float) item.Numero);
                            break;
                        case "SEN":
                            total = calculadora.Seno((float) item.Numero);
                            break;
                        case "COS":
                            total = calculadora.Cos((float) item.Numero);
                            break;
                        case "TAN":
                            total = calculadora.Tan((float) item.Numero);
                            break;
                        case "POT":
                            total = calculadora.Potencia((float) total, (float) item.Numero);
                            break;
                            
                    }
                }
                
            }
        }
 
        textoCalculadora.setText(String.valueOf(total));
        NumeroTotal = (double) total;
        ListadoOperaciones.clear();
    }//GEN-LAST:event_IGUALActionPerformed

    private void TANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TANActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "TAN"));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        NumeroTotal = 0;
    }//GEN-LAST:event_TANActionPerformed

    private void SENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENActionPerformed
        // TODO add your handling code here:
        textoCalculadora.setText("");
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(0, "SEN"));
        ListadoOperaciones.add(new CalculadoraGrafica.OperationChain(NumeroTotal, null));
        NumeroTotal = 0;
    }//GEN-LAST:event_SENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGrafica().setVisible(true);
            }
        });
    }
    public class OperationChain{ 
        public double Numero;
        public String operacion;
        OperationChain(double numerodado, String operaciondada ){
            this.Numero = numerodado;
            this.operacion = operaciondada;
        }
        
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COS;
    private javax.swing.JButton DIV;
    private javax.swing.JButton IGUAL;
    private javax.swing.JButton MENOS;
    private javax.swing.JButton MULTI;
    private javax.swing.JButton NUM0;
    private javax.swing.JButton NUM1;
    private javax.swing.JButton NUM2;
    private javax.swing.JButton NUM3;
    private javax.swing.JButton NUM4;
    private javax.swing.JButton NUM5;
    private javax.swing.JButton NUM6;
    private javax.swing.JButton NUM7;
    private javax.swing.JButton NUM8;
    private javax.swing.JButton NUM9;
    private javax.swing.JButton POT;
    private javax.swing.JButton PUNTO;
    private javax.swing.JButton SEN;
    private javax.swing.JButton SUMA;
    private javax.swing.JButton TAN;
    private javax.swing.JTextField textoCalculadora;
    // End of variables declaration//GEN-END:variables
}
